[package]
name = "day7"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = "3.1.4"
httparse = { version = "1.10.1", features = ["std"] }
anyhow = "1"
num-bigint = "0.4.6"
num-traits = "0.2.19"
